### ISSUE TITLE
create pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/frontmatter-check#21]
In order to make the package discoverable with pre-commit, you need a `.pre-commit-hooks.yaml`

```yaml
id: frontmatter-check
name: frontmatter check
description: matches frontmatter
version: 0.0.1
```
