### ISSUE TITLE
[FEATURE] make rules case insensitive and add `--case-sensitivity` parameter

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/frontmatter-check#34]
﻿Given:
﻿
```yaml

﻿Date: 2019-10-01 11:00:00-07:00
Tags: Brett Terpstra, Bunch, Alfred, Workflow
Title: Quickly Set Your Environment with Bunch and Alfred
description: Discover how I use Bunch and Alfred to streamline my workflow with a
  simple URL scheme and custom workflows.

```

with a config of

```yaml
patterns:
  - name: "Blog Posts"
    pattern: "content/*.md" # match ALL `.md` files in the content folder
    rules:
      - field_name: title
      - field_name: description
      - field_name: date
```

the values **fail**.

This makes sense considering `"Title" != "title"` but I think it's reasonable to normalize case in checks.

I also think you can consider values that should be case sensitive when the system in use requires it. 

This update could be two stages:

- [ ] Make rules case-insensitive
- [ ] Make global, sectional, and individual settings for case-sensitivity
